{
    'name': 'Reset Contacts Password',
    'version': '19.0.1.0.0',
    'summary': "Reset user's password from partner form",
    'description': "This module allows administrators to reset a user's password directly from the partner form view. It works for all type of users including internal and portal users.",
    'author': 'Attefeh Falah',
    'company': 'Tech Stars SPC',
    'maintainer': 'Tech Stars SPC',
    'website': 'https://www.attefehfalah.com',
    'support': 'attefehfalah@gmail.com',
    'category': 'Contact',
    'depends': ['contacts'],
    'data': [
        'security/password_reset_security.xml',
        'security/ir.model.access.csv',
        'wizard/partner_reset_password_views.xml',
        'views/res_partner_views.xml',
    ],
    'images': [
        'static/description/cover.png',
        'static/description/Screenshot 01.png',
        'static/description/Screenshot 02.png',
    ],
    'price': 0,
    'currency': 'USD',
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}